[package]
name = "advent"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
argh = "0.1.6"
either = "1.6.1"
hashbrown = "0.11.2"
itermore = "0.2.0"
itertools = "0.10.1"
peter = "0.2.1"
regex-macro = "0.1.1"
vectrix = "0.2.0"
ascii-art = { path = "../ascii-art" }
