[package]
name = "advent-cli"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.40"
clap = "3.0.0-beta.2"
curl = "0.4.37"
open = "1.7.0"
serde = { version = "1.0.126", features = ["derive"] }
toml = "0.5.8"
