[package]
name = "advent-cli"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.57"
argh = "0.1.7"
curl = "0.4.43"
open = "2.1.3"
serde = { version = "1.0.137", features = ["derive"] }
toml = "0.5.9"
