[package]
name = "advent-2019"
version = "0.1.0"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2018"
publish = false

[dependencies]
itertools = "0.10.0"
math = { path = "../crates/math" }
regex-macro = "0.1.1"
vectrix = { path = "../crates/vectrix-ext" }
