name: build

on: [push, pull_request]

env:
  RUSTFLAGS: --deny warnings

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.ADVENT_INPUT_GITHUB_TOKEN }}
        repository: rossmacarthur/advent-input
        path: input

    - name: Setup Rust
      run: rustup show

    - name: Rustfmt
      run: cargo fmt -- --check

    - name: Clippy
      run: cargo clippy --workspace --all-targets

    - name: Test
      run: cargo test --workspace --all-targets --release
