name: build

on: [push, pull_request]

env:
  RUSTFLAGS: --warn elided-lifetimes-in-paths --deny warnings

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust
      run: rustup show

    - name: Rustfmt
      run: cargo fmt -- --check

    - name: Clippy
      run: cargo clippy --workspace --all-targets -- -A clippy::many_single_char_names

    - name: Test
      run: cargo test --workspace --all-targets --release
